# Generated by Django 5.0.7 on 2024-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FitProfile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="password",
        ),
        migrations.RemoveField(
            model_name="login",
            name="username",
        ),
        migrations.AddField(
            model_name="login",
            name="age",
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="body_fat",
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="body_type",
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="current_height",
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="current_weight",
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="diet",
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="email",
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="exercise_frequency",
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="gender",
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="motivation",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="name",
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="nutritional_plan",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="progression_plan",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="self_assessment",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="sleep",
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="stress_level",
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="target_weight",
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="tracking_method",
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="type_of_workout",
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="workout_plan",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
