# Generated by Django 5.0.7 on 2024-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FitProfile", "0002_remove_login_password_remove_login_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="age",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="body_fat",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="current_height",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="current_weight",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="exercise_frequency",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="motivation",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="self_assessment",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="sleep",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="target_weight",
            field=models.CharField(max_length=100),
        ),
    ]
