# Generated by Django 5.0.7 on 2024-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FitProfile", "0003_alter_login_age_alter_login_body_fat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="password",
            field=models.CharField(default=True, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="username",
            field=models.CharField(default=True, max_length=10000),
            preserve_default=False,
        ),
    ]
