# Generated by Django 5.0.7 on 2024-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FitProfile", "0004_login_password_login_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="introduction",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
