# Generated by Django 5.0.7 on 2024-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FitProfile", "0005_login_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="otp",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
